# Generated by Django 5.0 on 2024-09-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearing_app', '0002_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
