# Generated by Django 5.0 on 2024-09-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearing_app', '0005_customer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp_generated_at',
        ),
    ]
