# Generated by Django 5.0 on 2024-09-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearing_app', '0006_remove_customer_is_verified_remove_customer_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearing_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearing_app.customer')),
            ],
        ),
    ]
