# Generated by Django 5.0 on 2024-10-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearing_app', '0009_customer_reset_code_customer_reset_code_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resources',
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('image', 'Image'), ('link', 'Link')], max_length=10)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='course_resources/')),
                ('resource_link', models.URLField(blank=True, null=True)),
                ('resource_name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='Elearing_app.course')),
            ],
        ),
    ]
